version: "3.9"

services:
  # Postgres service
  database:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: moroz.taras.pass
      # Trust all connections
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
